### ISSUE TITLE
Add feature to allow enforcement of MFA via CLi

### ISSUE THREAD

**Issue by garym-krrv** [terraform-module/terraform-aws-enforce-mfa#52]
## Motivation

Currently this module does not enforce MFA for anyone using AWS cli. This module only enforces MFA with using the AWS console.

## Additional context

To enforce MFA on CLI, the additional Condition/Policy needs to be applied to the IAM policy. This can be applied to the existing SID of DenyAllExceptListedIfNoMFA or create a New sid and dynamic statement that enforces CLI and Console access as per example

dynamic "statement" {
    for_each = var.manage_explicit_deny_cli ? [1] : []

    content {
      sid    = "DenyAllExceptListedIfNoMFAWithCLi"
      effect = "Deny"
      not_actions = [
        "iam:CreateVirtualMFADevice",
        "iam:EnableMFADevice",
        "iam:GetUser",
        "iam:ListMFADevices",
        "iam:ListVirtualMFADevices",
        "iam:ResyncMFADevice",
        "sts:GetSessionToken"
      ]
      resources = ["*"]
      condition {
        test     = "BoolIfExists"
        variable = "aws:MultiFactorAuthPresent"
        values   = ["false", ]
      }
       condition {
        test     = "BoolIfExists"
        variable = "aws:ViaAWSService"
        values   = ["false", ]
      }
    }
}

**Comment by ivankatliarchuk** [comment]
Hi @garym-krrv feel free to add this feature

**Comment by garym-krrv** [comment]
Will do. Thank you.
